apiVersion: v1
kind: Pod
metadata:
  labels:
    app: backend
    env: production
  name: busybox-pod
spec:
  containers:
  - name: busybox-container
    image: busybox
    args:
    - sleep
    - "1000000"